import * as ActionTypes from '../action-types';

const DEFAULT_STATE = {
  muted: true,
  settings: {
    rows: 10,
    columns: 10,
    humanCharacters: [
      {
        id: 1,
        name: 'Victor',
        type: 'hero',
        speed: 6,
        image: 'warrior',
        fill: 'C',
        maxHp: 8,
        hp: 4,
        attack: +4,
        ac: 0,
        damage: [2, 6],
        player: 'human',
        initiative: 16,
      },
      {
        id: 4,
        name: 'Fortuna',
        type: 'hero',
        speed: 6,
        image: 'fortuna',
        fill: 'C',
        maxHp: 5,
        hp: 5,
        attack: +8,
        ac: 10,
        damage: [1, 4],
        player: 'human',
        initiative: 24,
      },
    ],
    aiCharacters: [
      {
        id: 2,
        name: 'Goblin',
        type: 'enemy',
        speed: 5,
        image: 'goblin',
        fill: 'C',
        maxHp: 6,
        hp: 6,
        attack: 0,
        ac: 8,
        damage: [1, 4],
        player: 'ai',
        initiative: 18,
      },
      {
        id: 3,
        name: 'Golem',
        type: 'enemy',
        speed: 5,
        image: 'golem',
        fill: 'C',
        maxHp: 8,
        hp: 8,
        attack: -2,
        ac: 8,
        damage: [2, 6],
        player: 'ai',
        initiative: 12,
      },
    ],
    fill: {
      rows: 10,
      obstacles() {
        return Math.round(this.rows * (this.rows / 2.5) - this.rows * 1.5);
      },
      characters() {
        return [
          {
            id: 1,
            name: 'Victor',
            type: 'hero',
            speed: 6,
            image: 'warrior',
            index: 4,
            fill: 'C',
            sound: 'warrior',
            maxHp: 4,
            hp: 4,
            attack: +2,
            ac: 0,
            damage: [2, 6],
            player: 'human',
            initiative: 24,
          },
          {
            id: 4,
            name: 'Fortuna',
            type: 'hero',
            index: 5,
            speed: 6,
            image: 'fortuna',
            fill: 'C',
            maxHp: 5,
            hp: 5,
            attack: +8,
            ac: 10,
            damage: [1, 4],
            player: 'human',
            initiative: 24,
          },
          {
            id: 2,
            name: 'Golem',
            type: 'enemy',
            speed: 5,
            image: 'golem',
            index: 97,
            fill: 'C',
            maxHp: 8,
            hp: 8,
            attack: -2,
            ac: 8,
            damage: [2, 6],
            player: 'ai',
            initiative: 12,
          },
          {
            id: 3,
            name: 'Goblin',
            type: 'enemy',
            speed: 5,
            image: 'goblin',
            index: 96,
            fill: 'C',
            sound: 'goblin',
            maxHp: 6,
            hp: 6,
            attack: 0,
            ac: 8,
            damage: [1, 4],
            player: 'ai',
            initiative: 18,
          },
        ];
      },
      characters1: [
        {
          id: 1,
          name: 'Victor',
          type: 'hero',
          speed: 6,
          image: 'warrior',
          index: 4,
          fill: 'C',
          sound: 'warrior',
          maxHp: 4,
          hp: 2,
          attack: +2,
          ac: 0,
          damage: [2, 6],
          player: 'human',
          initiative: 24,
        },
        {
          id: 3,
          name: 'Goblin',
          type: 'enemy',
          speed: 5,
          image: 'goblin',
          index: 96,
          fill: 'C',
          sound: 'goblin',
          maxHp: 6,
          hp: 6,
          attack: 0,
          ac: 8,
          damage: [1, 4],
          player: 'ai',
          initiative: 18,
        },
      ],
    },
  },
};

const ConfigReducer = (state = DEFAULT_STATE, action) => {
  switch (action.type) {
    case ActionTypes.TOGGLE_SOUND: {
      return {
        ...state,
        muted: action.muted,
      };
    }
    default:
      return state;
  }
};

export default ConfigReducer;
